services:
  dance-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dance-bot
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - TZ=Europe/Madrid
    restart: unless-stopped
    ports:
      - "5555:5555"  # Prisma Studio
    networks:
      - dance-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dance-bot-network:
    driver: bridge
